learning_templates/basic_app/urls.py
from django.urls import path, re_path, include
from basic_app.views import relative, other

app_name = 'basic_app'

urlpatterns = [
    path('relative/', relative, name='relative'),
    path('other/', other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context=context_dict)


def other(request):
    return render(request, 'basic_app/other.html', context={})


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html', context={})

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static  'bootstrap/css/bootstrap.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container">
        <ul class="navbar-nav">
            <li>
                <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
            </li>
            <li>
                <a class="navbar-link" href="{% url 'admin:index' %}">ADMIN PAGE</a>
            </li>
            <li>
                <a class="navbar-link" href="{% url 'basic_app:other' %}">OTHER</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h1>THIS IS INDEX.html IS SHOWING!</h1>
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ number|add:'24' }}</h1>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>THIS IS AN EXAMPLE OF TEMPLATE INHERITANCE</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
<a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a><br>
<a href="{% url 'admin:index' %}">THE ADMIN PAGE</a><br>
<a href="{% url 'index' %}">THE INDEX PAGE</a><br>
</body>
</html>